In [12]:
import sys, os
sys.path.append(os.pardir)
from common.functions import sigmoid, softmax
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient
class simpleNet:
  def __init__(self):
    self.W=np.random.randn(2,3) # 정규분포로 초기화
  def predict(self,x): # 예측 수행
    return np.dot(x, self.W)
  def loss(self,x,t): # 손실함수의 값 구함(x는 입력데이터, t는 정답레이블)
    z=self.predict(x) 
    y=softmax(z)
    loss=cross_entropy_error(y,t)

    return loss

net=simpleNet()
print(net.W)
x=np.array([0.6,0.9])
p=net.predict(x)
print(p)
print(np.argmax(p))
t=np.array([0,0,1])
print(net.loss(x,t))
def f(W): # net.W을 인수로 받아 손실함수 계산하는 새로운 함수 f를 정의
  return net.loss(x,t)
dw=numerical_gradient(f,net.W) 
print(dw)
#f=lamda w: net.loss(x,t)
#dw=numerical_gradient(f,net.W)

[[ 1.48382436  1.0402586  -0.37158765]
 [ 0.41325548 -0.41823927 -1.39092008]]
[ 1.26222454  0.24773982 -1.47478066]
0
3.0928248376142635
[[ 0.42035753  0.15241711 -0.57277464]
 [ 0.6305363   0.22862566 -0.85916196]]


In [2]:
import sys, os
sys.path.append(os.pardir)
from common.functions import *
from common.gradient import numerical_gradient

class TwoLayerNet:
    def __init__(self,input_size,hidden_size,output_size,weight_init_std=0.01):
        # 가중치 초기화
        self.params={}
        self.params['W1']=weight_init_std*\
                            np.random.randn(input_size,hidden_size)
        self.params['b1']=np.zeros(hidden_size)
        self.params['W2']=weight_init_std*\
                            np.random.randn(hidden_size,output_size)
        self.params['b2']=np.zeros(output_size)

    def predict(self,x):
        W1,W2=self.params['W1'], self.params['W2']
        b1,b2=self.params['b1'], self.params['b2']

        a1=np.dot(x,W1)+b1
        z1=sigmoid(a1)
        a2=np.dot(z1,W2)+b2
        y=softmax(a2)

        return y

        # x:입력데이터,t:정답레이블
        # 손실 함수 값을 계산하는 메서드
    def loss(self,x,t):
        y=self.predict(x)

        return cross_entropy_error(y,t)

    def accuracy(self,x,t):
        y=self.predict(x)
        y=np.argmax(y, axis=1)
        t=np.argmax(t, axis=1)

        accuracy=np.sum(y==t)/float(x.shape[0])
        return accuracy

        # x:입력데이터, t:정답레이블
        # 각 매개변수의 기울기 계산
    def numercal_gradient(self,x,t):
        loss_W=lambda W: self.loss(x,t)

        grads={}
        grads['W1']=numercal_gradient(loss_W, self,params['W1'])
        grads['b1']=numercal_gradient(loss_W, self,params['b1'])
        grads['W2']=numercal_gradient(loss_W, self,params['W2'])
        grads['b2']=numercal_gradient(loss_W, self,params['b2'])

        return grads

net=TwoLayerNet(input_size=784, hidden_size=100, output_size=10)
print(net.params['W1'].shape) # params에 이 신경망에 필요한 매개변수가 모두 저장됨
print(net.params['b1'].shape) # params에 저장된 가중치 매개변수가 예측 처리(순방향 처리)에서 사용됨
print(net.params['W2'].shape)
print(net.params['b2'].shape)
x=np.random.rand(100,784) # 더미 입력 데이터 100장 분량 
y=net.predict(x) # 예측 처리(순방향 처리) 실행 방법

(784, 100)
(100,)
(100, 10)
(10,)


In [19]:
import sys, os
sys.path.append(os.pardir)
from common.functions import *
from common.gradient import numerical_gradient

class TwoLayerNet:
    def __init__(self,input_size,hidden_size,output_size,weight_init_std=0.01):
        # 가중치 초기화
        self.params={}
        self.params['W1']=weight_init_std*\
                            np.random.randn(input_size,hidden_size)
        self.params['b1']=np.zeros(hidden_size)
        self.params['W2']=weight_init_std*\
                            np.random.randn(hidden_size,output_size)
        self.params['b2']=np.zeros(output_size)

    def predict(self,x):
        W1,W2=self.params['W1'], self.params['W2']
        b1,b2=self.params['b1'], self.params['b2']

        a1=np.dot(x,W1)+b1
        z1=sigmoid(a1)
        a2=np.dot(z1,W2)+b2
        y=softmax(a2)

        return y

        # x:입력데이터,t:정답레이블
        # 손실 함수 값을 계산하는 메서드
    def loss(self,x,t):
        y=self.predict(x)

        return cross_entropy_error(y,t)

    def accuracy(self,x,t):
        y=self.predict(x)
        y=np.argmax(y, axis=1)
        t=np.argmax(t, axis=1)

        accuracy=np.sum(y==t)/float(x.shape[0])
        return accuracy

        # x:입력데이터, t:정답레이블
        # 각 매개변수의 기울기 계산
    def numerical_gradient(self,x,t):
        loss_W=lambda W: self.loss(x,t)

        grads={}
        grads['W1']=numercal_gradient(loss_W, self,params['W1'])
        grads['b1']=numercal_gradient(loss_W, self,params['b1'])
        grads['W2']=numercal_gradient(loss_W, self,params['W2'])
        grads['b2']=numercal_gradient(loss_W, self,params['b2'])

        return grads

x=np.random.rand(100,784) # 더미 입력 데이터(100장 분량)
t=np.random.rand(100,10) # 더미 정답 레이블(100장 분량)

grads=net.numerical_gradient(x,t) # 기울기 계산
# grads에는 params에 대응하는 각 매개변수의 기울기 저장
# numberical_gradient()메서드를 사용해 기울기 계산 시 grads에 기울기 정보 저장
grads['W1'].shape
grads['b1'].shape
grads['W2'].shape
grads['b2'].shape

AttributeError: 'simpleNet' object has no attribute 'numerical_gradient'

In [20]:
import sys, os
sys.path.append(os.pardir)
from common.functions import *
from common.gradient import numerical_gradient

import numpy as np
from dataset.mnist import load_mnist
from two_layer_net import TwoLayerNet


class TwoLayerNet:
    def __init__(self,input_size,hidden_size,output_size,weight_init_std=0.01):
        # 가중치 초기화
        self.params={}
        self.params['W1']=weight_init_std*\
                            np.random.randn(input_size,hidden_size)
        self.params['b1']=np.zeros(hidden_size)
        self.params['W2']=weight_init_std*\
                            np.random.randn(hidden_size,output_size)
        self.params['b2']=np.zeros(output_size)

    def predict(self,x):
        W1,W2=self.params['W1'], self.params['W2']
        b1,b2=self.params['b1'], self.params['b2']

        a1=np.dot(x,W1)+b1
        z1=sigmoid(a1)
        a2=np.dot(z1,W2)+b2
        y=softmax(a2)

        return y

        # x:입력데이터,t:정답레이블
        # 손실 함수 값을 계산하는 메서드
    def loss(self,x,t):
        y=self.predict(x)

        return cross_entropy_error(y,t)

    def accuracy(self,x,t):
        y=self.predict(x)
        y=np.argmax(y, axis=1)
        t=np.argmax(t, axis=1)

        accuracy=np.sum(y==t)/float(x.shape[0])
        return accuracy

        # x:입력데이터, t:정답레이블
        # 각 매개변수의 기울기 계산
    def numerical_gradient(self,x,t):
        loss_W=lambda W: self.loss(x,t)

        grads={}
        grads['W1']=numerical_gradient(loss_W, self,params['W1'])
        grads['b1']=numerical_gradient(loss_W, self,params['b1'])
        grads['W2']=numerical_gradient(loss_W, self,params['W2'])
        grads['b2']=numerical_gradient(loss_W, self,params['b2'])

        return grads

(x_train, t_train), (x_test, t_test)=\
  load_mnist(normalize=True, one_hot_label=True)

train_loss_list=[]

# 하이퍼파라미터
iters_num=10000 # 반복횟수
train_size=x_train.shape[0]
batch_size=100 # 미니배치 크기
learning_rate=0.1
network=TwoLayerNet(input_size=784, hidden_size=50, output_size=10)

for i in range(iters_num):
  # 미니배치 획득
  batch_mask=np.random.choice(train_size, batch_size)
  x_batch=x_train[batch_mask]
  t_batch=t_train[batch_mask]

  # 기울기 계산
  grad=network.numerical_gradient(x_batch, t_batch)
  # grad=network.gradient(x_batch, t_batch) 성능 개선판

  # 매개변수 갱신
  for key in ('W1', 'b1', 'W2', 'b2'):
    network.params[key]-=learning_rate*grad[key]

  #학습 경과 기록
  loss=network.loss(x_batch, t_batch)
  train_loss_list.append[loss]

NameError: name 'params' is not defined